spring:
  application:
    name: proposta-fin-app

  datasource:
    url: jdbc:postgresql://localhost:5432/propostafindb
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
rabbitmq:
  exchanges:
    proposta-pendente: proposta-pendente.ex
    proposta-pendente-dlx: proposta-pendente-dlx.ex
    proposta-concluida: proposta-concluida.ex
  queue:
    proposta:
      concluida: proposta-concluida.ms-proposta

scheduler:
  propostas:
    nao-integradas:
      intervalo: 10 # Intervalo em minutos
#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0